### ISSUE TITLE
GetRealmsIndexAsync() failing for TW

### ISSUE THREAD

**Issue by bonesoul** [blizzard-net/warcraft#211]
basically I do have an client & secret for us endpoints.

using these api client id and secret values i can make calls to all realms except tw:

`                var result = await client.GetRealmsIndexAsync(@namespace);`

```
16:39:22 [INF] [RealmUpdater] querying realms of taiwan failed with System.Net.Http.HttpRequestException: Response code 401 (Unauthorized) does not indicate success. Request: https://tw.api.blizzard.com/data/wow/realm/index?namespace=dynamic-tw&locale=zh_TW
   at ArgentPonyWarcraftClient.WarcraftClient.GetAsync[T](String requestUri, String accessToken)
   at ArgentPonyWarcraftClient.WarcraftClient.GetAsync[T](String requestUri)
   at ArgentPonyWarcraftClient.WarcraftClient.GetRealmsIndexAsync(String namespace, Region region, Locale locale)
   at ArgentPonyWarcraftClient.WarcraftClient.GetRealmsIndexAsync(String namespace)
   at Wowtrack.Data.Updater.Jobs.Realm.RealmUpdater.GetRealmsForRegion(Region region, Locale locale) in C:\Coding\wowtrack.gg\core_dotnet\src\tools\updater\Jobs\Realm\RealmUpdater.cs:line 106..
```
 tw version fails:

`https://tw.api.blizzard.com/data/wow/realm/index?namespace=dynamic-tw&locale=zh_TW&access_token=TOKEN`

**Comment by bonesoul** [comment]
I have further debugged the issue, the library can't get an access token for tw:

![image](https://user-images.githubusercontent.com/73215/226638285-34286b94-b54a-4da8-a0d3-64f465a21e6f.png)

**Comment by bonesoul** [comment]
created a pr for this: https://github.com/blizzard-net/warcraft/pull/212/files

**Comment by bonesoul** [comment]
doc now suggests https://develop.battle.net/documentation/guides/using-oauth for EU, US and APAC regions.

**Comment by bonesoul** [comment]
updated the PR for according to latest oauth host changes.
